# Server Port
# server.port=8080
server.port=${PORT:8080}

# Database Configuration (TiDB Cloud)
spring.datasource.url=jdbc:mysql://gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/asset_tracker?useSSL=true&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=3AanjvP5Xvf4WV8.root
spring.datasource.password=fyYhwZB13Gs85LOU
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Custom JWT Secret & Expiration (24 hours in ms)
jwt.secret=SUPER_SECRET_KEY_1234567890_MUST_BE_LONG_ENOUGH_FOR_HS256
jwt.expiration=3600000

server.error.include-message=always
